version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: Install make
          command: sudo apt-get install make
      
      - run:
          name: ls test files
          command: ls -l test

      - run:
          name: Test
          command: make test
